language: python

python:
    - 2.7
    - 3.4

sudo: false

before_install:
    - pip install coveralls
    - pip install coverage

install:
    - pip install -e . 

script:
    - coverage run -a `which py.test` abjad

after_success:
    coveralls